version: 0.2

env:
  variables:
    NVD_API_KEY: "feced4ae-847a-43e9-a18e-bb7bec361b0e"

phases:
  install:
    runtime-versions:
      nodejs: 14  # Atualize para uma versão mais recente se necessário
      java: corretto17  # Necessário para o OWASP Dependency-Check
    commands:
      - echo "Installing NPM dependencies..."
      - npm install
      - echo "Installing OWASP Dependency-Check..."
      - curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
      - unzip dependency-check.zip -d /opt/
      - ls -l /opt/  # Verifica a pasta criada após unzip
      - chmod +x /opt/dependency-check/bin/dependency-check.sh
  pre_build:
    commands:
      - echo "Updating OWASP Dependency-Check database..."
      - /opt/dependency-check/bin/dependency-check.sh --updateonly --apiKey $NVD_API_KEY
      - echo "Running OWASP Dependency-Check..."
      - mkdir -p reports
      - /opt/dependency-check/bin/dependency-check.sh --project "MyApp" --scan . --out reports/ --format HTML --apiKey $NVD_API_KEY
      - echo "OWASP Dependency-Check completed"
  build:
    commands:
      - echo "Build phase - compiling application if necessary"
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Saving OWASP Dependency-Check report"
      - echo "Uploading OWASP Dependency-Check report to S3"
      - aws s3 cp reports/dependency-check-report.html s3://meu-bucket-owasp/

artifacts:
  files:
    - '**/*'
    - 'reports/dependency-check-report.html'  # Inclui o relatório de segurança como artefato
  discard-paths: no
